name: JSX 2 OverReact
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Run Tests
        run: deno test
  deploy:
    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Build App
        run: deno task build

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: jsx2overreact # the name of the project on Deno Deploy
          entrypoint: dist/server.js # the entrypoint to deploy
